[build]
target = "i586-unknown-none.json"
rustflags = [
    "-C", "relocation-model=static", 
    "-C", "link-args=-T src/link.ld",
    "-C", "llvm-args=--inline-threshold=275",
]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
