[build]
# TODO: Since rust-analyzer is throwing errors, we'll set a temporary target here.
target = "i586-unknown-linux-musl"
# target = "i586-unknown-none.json"
rustflags = [
    "-Zunstable-options",
    "-C", "target-cpu=i386",
    "-C", "relocation-model=static", 
    "-C", "link-args=-T src/link.ld",
    "-C", "llvm-args=--inline-threshold=275",
]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
