[build]
target = "i586-unknown-linux-gnu"
rustflags = ["-C", "relocation-model=static", "-C", "lto", "-C", "link-args=--image-base=0x00100000 --omagic"]

[target.i586-unknown-linux-gnu]
linker = "/opt/homebrew/opt/llvm/bin/ld.lld"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
