[package]
authors = ["Nerry <108566+neri@users.noreply.github.com>"]
edition = "2018"
name = "kernel"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2.1"
byteorder = {version = "1", default-features = false}
megstd = {path = "../../lib/megstd/"}
myosabi = {path = "../../lib/myosabi/"}
toeboot = {path = "../../lib/toeboot/"}
wasm = {path = "../../lib/wasm/"}

# futures-util = {default-features = false, features = ["alloc"], version = "0.3"}
