//
// This file is automatically generated at build time. DO NOT EDIT DIRECTLY.
//

/// '─' U+2500 BOX DRAWINGS LIGHT HORIZONTAL
pub const HORIZONTAL: char = '\u{2500}';

/// '│' U+2502 BOX DRAWINGS LIGHT VERTICAL
pub const VERTICAL: char = '\u{2502}';

/// '┌' U+250C BOX DRAWINGS LIGHT DOWN AND RIGHT
pub const TOP_LEFT: char = '\u{250c}';

/// '┐' U+2510 BOX DRAWINGS LIGHT DOWN AND LEFT
pub const TOP_RIGHT: char = '\u{2510}';

/// '└' U+2514 BOX DRAWINGS LIGHT UP AND RIGHT
pub const BOTTOM_LEFT: char = '\u{2514}';

/// '┘' U+2518 BOX DRAWINGS LIGHT UP AND LEFT
pub const BOTTOM_RIGHT: char = '\u{2518}';

/// '┴' U+2534 BOX DRAWINGS LIGHT UP AND HORIZONTAL
pub const T_UP: char = '\u{2534}';

/// '┬' U+252C BOX DRAWINGS LIGHT DOWN AND HORIZONTAL
pub const T_DOWN: char = '\u{252c}';

/// '┤' U+2524 BOX DRAWINGS LIGHT LEFT AND VERTICAL
pub const T_LEFT: char = '\u{2524}';

/// '├' U+251C BOX DRAWINGS LIGHT RIGHT AND VERTICAL
pub const T_RIGHT: char = '\u{251c}';

/// '┼' U+253C BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL
pub const CROSS: char = '\u{253c}';

/// Box Drawing Characters
#[allow(non_camel_case_types)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BoxDrawingChar {
    /// '─' U+2500 BOX DRAWINGS LIGHT HORIZONTAL
    HORIZONTAL,
    /// '│' U+2502 BOX DRAWINGS LIGHT VERTICAL
    VERTICAL,
    /// '┌' U+250C BOX DRAWINGS LIGHT DOWN AND RIGHT
    TOP_LEFT,
    /// '┐' U+2510 BOX DRAWINGS LIGHT DOWN AND LEFT
    TOP_RIGHT,
    /// '└' U+2514 BOX DRAWINGS LIGHT UP AND RIGHT
    BOTTOM_LEFT,
    /// '┘' U+2518 BOX DRAWINGS LIGHT UP AND LEFT
    BOTTOM_RIGHT,
    /// '┴' U+2534 BOX DRAWINGS LIGHT UP AND HORIZONTAL
    T_UP,
    /// '┬' U+252C BOX DRAWINGS LIGHT DOWN AND HORIZONTAL
    T_DOWN,
    /// '┤' U+2524 BOX DRAWINGS LIGHT LEFT AND VERTICAL
    T_LEFT,
    /// '├' U+251C BOX DRAWINGS LIGHT RIGHT AND VERTICAL
    T_RIGHT,
    /// '┼' U+253C BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL
    CROSS,
}

impl BoxDrawingChar {
    /// Convert to the corresponding `char`.
    pub const fn to_char(self) -> char {
        match self {
            Self::HORIZONTAL => '\u{2500}',
            Self::VERTICAL => '\u{2502}',
            Self::TOP_LEFT => '\u{250c}',
            Self::TOP_RIGHT => '\u{2510}',
            Self::BOTTOM_LEFT => '\u{2514}',
            Self::BOTTOM_RIGHT => '\u{2518}',
            Self::T_UP => '\u{2534}',
            Self::T_DOWN => '\u{252c}',
            Self::T_LEFT => '\u{2524}',
            Self::T_RIGHT => '\u{251c}',
            Self::CROSS => '\u{253c}',
        }
    }

    /// Convert from a `char` if possible.
    pub const fn from_char(ch: char) -> Option<Self> {
        match ch as u32 {
            0x2500 => Some(Self::HORIZONTAL),
            0x2502 => Some(Self::VERTICAL),
            0x250c => Some(Self::TOP_LEFT),
            0x2510 => Some(Self::TOP_RIGHT),
            0x2514 => Some(Self::BOTTOM_LEFT),
            0x2518 => Some(Self::BOTTOM_RIGHT),
            0x251c => Some(Self::T_RIGHT),
            0x2524 => Some(Self::T_LEFT),
            0x252c => Some(Self::T_DOWN),
            0x2534 => Some(Self::T_UP),
            0x253c => Some(Self::CROSS),
            _ => None,
        }
    }

    /// Returns all variants.
    #[inline]
    pub const fn all_variants() -> &'static [Self] {
        &[
            Self::HORIZONTAL,
            Self::VERTICAL,
            Self::TOP_LEFT,
            Self::TOP_RIGHT,
            Self::BOTTOM_LEFT,
            Self::BOTTOM_RIGHT,
            Self::T_UP,
            Self::T_DOWN,
            Self::T_LEFT,
            Self::T_RIGHT,
            Self::CROSS,
        ]
    }

    #[inline]
    pub(crate) const fn udlr(&self) -> u8 {
        match self {
            Self::HORIZONTAL => 0b00001010,
            Self::VERTICAL => 0b00000101,
            Self::TOP_LEFT => 0b00000110,
            Self::TOP_RIGHT => 0b00001100,
            Self::BOTTOM_LEFT => 0b00000011,
            Self::BOTTOM_RIGHT => 0b00001001,
            Self::T_UP => 0b00001011,
            Self::T_DOWN => 0b00001110,
            Self::T_LEFT => 0b00001101,
            Self::T_RIGHT => 0b00000111,
            Self::CROSS => 0b00001111,
        }
    }

    #[inline]
    pub(crate) const fn from_udlr(udlr: u8) -> Option<Self> {
        match udlr {
            0b00000011 => Some(Self::BOTTOM_LEFT),
            0b00000101 => Some(Self::VERTICAL),
            0b00000110 => Some(Self::TOP_LEFT),
            0b00000111 => Some(Self::T_RIGHT),
            0b00001001 => Some(Self::BOTTOM_RIGHT),
            0b00001010 => Some(Self::HORIZONTAL),
            0b00001011 => Some(Self::T_UP),
            0b00001100 => Some(Self::TOP_RIGHT),
            0b00001101 => Some(Self::T_LEFT),
            0b00001110 => Some(Self::T_DOWN),
            0b00001111 => Some(Self::CROSS),
            _ => None,
        }
    }
}

/// ASCII characters and DEC Special Graphics box drawing characters
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Ord, PartialOrd)]
pub struct BoxAscii(pub u8);

impl BoxAscii {
    /// Convert from a `char` if possible.
    pub const fn from_char(ch: char) -> Option<Self> {
        match ch as u32 {
            0..127 => Some(Self(ch as u8)),
            0x2500 => Some(Self(0xf1)),
            0x2502 => Some(Self(0xf8)),
            0x250c => Some(Self(0xec)),
            0x2510 => Some(Self(0xeb)),
            0x2514 => Some(Self(0xed)),
            0x2518 => Some(Self(0xea)),
            0x251c => Some(Self(0xf4)),
            0x2524 => Some(Self(0xf5)),
            0x252c => Some(Self(0xf7)),
            0x2534 => Some(Self(0xf6)),
            0x253c => Some(Self(0xee)),
            _ => None,
        }
    }

    /// Convert to a `char` if possible.
    pub const fn to_char(self) -> Option<char> {
        match self.0 {
            0..127 => Some(self.0 as char),
            0xea => Some(BOTTOM_RIGHT),
            0xeb => Some(TOP_RIGHT),
            0xec => Some(TOP_LEFT),
            0xed => Some(BOTTOM_LEFT),
            0xee => Some(CROSS),
            0xf1 => Some(HORIZONTAL),
            0xf4 => Some(T_RIGHT),
            0xf5 => Some(T_LEFT),
            0xf6 => Some(T_UP),
            0xf7 => Some(T_DOWN),
            0xf8 => Some(VERTICAL),
            _ => None,
        }
    }

    /// Convert to a fallback ASCII `char` if possible.
    pub const fn to_fallback_ascii(self) -> Option<char> {
        match self.0 {
            0..127 => Some(self.0 as char),
            0xea => Some('+'),
            0xeb => Some('+'),
            0xec => Some('+'),
            0xed => Some('+'),
            0xee => Some('+'),
            0xf1 => Some('-'),
            0xf4 => Some('+'),
            0xf5 => Some('+'),
            0xf6 => Some('+'),
            0xf7 => Some('+'),
            0xf8 => Some('|'),
            _ => None,
        }
    }
}
