use std::{
    collections::BTreeMap,
    fs::{File, read_to_string},
    io::*,
};

fn main() {
    {
        let mut lines = Vec::new();
        for line in read_to_string("./src/box_drawing.csv").unwrap().lines() {
            if !line.is_empty() && !line.starts_with("#") {
                lines.push(line.to_string());
            }
        }

        let mut os = File::create("./src/_generated/box_drawing.rs").unwrap();

        make_box_drawing(&mut os, lines.as_slice());

        println!("cargo:rerun-if-changed=./src/box_drawing.csv");
    }
}

fn make_box_drawing(os: &mut File, lines: &[String]) {
    write!(
        os,
        "//
// This file is automatically generated at build time. DO NOT EDIT DIRECTLY.
//
"
    )
    .unwrap();

    let mut identifiers = Vec::new();
    let mut unicodes = Vec::new();
    let mut asciis = Vec::new();
    let mut map_table = BTreeMap::new();

    for line in lines.iter().skip(1) {
        let fields: Vec<&str> = line.split(',').collect();
        let identifier = fields[0];
        let unicode = u32::from_str_radix(fields[1], 16).unwrap();
        let ascii_alt = u8::from_str_radix(fields[2], 16).unwrap();
        let ascii_fallback = fields[3].chars().next().unwrap() as u8;
        let udlr = parse_udlr(fields[4]);
        let description = trim_quotes(fields[5]).to_string();

        if identifiers.contains(&identifier) {
            panic!("Duplicate identifier: {}", identifier);
        }
        identifiers.push(identifier);
        if unicodes.contains(&unicode) {
            panic!("Duplicate unicode: U+{:04x}", unicode);
        }
        unicodes.push(unicode);
        if asciis.contains(&ascii_alt) {
            panic!("Duplicate ascii_alt: 0x{:02x}", ascii_alt);
        }
        asciis.push(ascii_alt);

        let description = format!(
            "'{}' U+{:04X} {}",
            char::from_u32(unicode).unwrap(),
            unicode,
            description,
        );

        writeln!(os, "\n/// {}", description).unwrap();

        map_table.insert(
            identifier,
            BoxDrawingChar {
                identifier: identifier.to_string(),
                unicode,
                ascii_alt: 0x80 | ascii_alt,
                ascii_fallback,
                udlr,
                description,
            },
        );

        writeln!(
            os,
            "pub const {}: char = '\\u{{{:04x}}}';",
            identifier, unicode
        )
        .unwrap();
    }

    write!(
        os,
        "
/// Box Drawing Characters
#[allow(non_camel_case_types)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BoxDrawingChar {{
"
    )
    .unwrap();

    for identifier in identifiers.iter() {
        let item = map_table.get(identifier).unwrap();
        writeln!(
            os,
            "    /// {}
    {},",
            item.description, item.identifier,
        )
        .unwrap();
    }

    write!(
        os,
        "}}

impl BoxDrawingChar {{
    /// Convert to the corresponding `char`.
    pub const fn to_char(self) -> char {{
        match self {{
"
    )
    .unwrap();

    for identifier in identifiers.iter() {
        let item = map_table.get(identifier).unwrap();
        writeln!(
            os,
            "            Self::{} => '\\u{{{:04x}}}',",
            item.identifier, item.unicode
        )
        .unwrap();
    }

    write!(
        os,
        "        }}
    }}

    /// Convert from a `char` if possible.
    pub const fn from_char(ch: char) -> Option<Self> {{
        match ch as u32 {{
"
    )
    .unwrap();

    let mut items = BTreeMap::new();
    for (_, item) in map_table.iter() {
        items.insert(
            item.unicode,
            format!(
                "            {:#04x} => Some(Self::{}),\n",
                item.unicode, item.identifier
            ),
        );
    }
    sort_and_write(os, &items);

    write!(
        os,
        "            _ => None,
        }}
    }}

    /// Returns all variants.
    #[inline]
    pub const fn all_variants() -> &'static [Self] {{
        &[
"
    )
    .unwrap();

    for identifier in identifiers.iter() {
        writeln!(os, "            Self::{},", identifier).unwrap();
    }

    write!(
        os,
        "        ]
    }}

    #[inline]
    pub(crate) const fn udlr(&self) -> u8 {{
        match self {{
"
    )
    .unwrap();

    for identifier in identifiers.iter() {
        let item = map_table.get(identifier).unwrap();
        writeln!(
            os,
            "            Self::{} => {:#010b},",
            item.identifier, item.udlr
        )
        .unwrap();
    }

    write!(
        os,
        "        }}
    }}

    #[inline]
    pub(crate) const fn from_udlr(udlr: u8) -> Option<Self> {{
        match udlr {{
"
    )
    .unwrap();

    let mut items = BTreeMap::new();
    for (_, item) in map_table.iter() {
        items.insert(
            item.udlr,
            format!(
                "            {:#010b} => Some(Self::{}),\n",
                item.udlr, item.identifier
            ),
        );
    }
    sort_and_write(os, &items);

    write!(
        os,
        "            _ => None,
        }}
    }}
}}

/// ASCII characters and DEC Special Graphics box drawing characters
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Ord, PartialOrd)]
pub struct BoxAscii(pub u8);

impl BoxAscii {{
    /// Convert from a `char` if possible.
    pub const fn from_char(ch: char) -> Option<Self> {{
        match ch as u32 {{
            0..127 => Some(Self(ch as u8)),
"
    )
    .unwrap();

    let mut items = BTreeMap::new();
    for (_, item) in map_table.iter() {
        items.insert(
            item.unicode,
            format!(
                "            {:#04x} => Some(Self({:#02x})),\n",
                item.unicode, item.ascii_alt
            ),
        );
    }
    sort_and_write(os, &items);

    write!(
        os,
        "            _ => None,
        }}
    }}

    /// Convert to a `char` if possible.
    pub const fn to_char(self) -> Option<char> {{
        match self.0 {{
            0..127 => Some(self.0 as char),
"
    )
    .unwrap();

    let mut items = BTreeMap::new();
    for (_, item) in map_table.iter() {
        items.insert(
            item.ascii_alt,
            format!(
                "            {:#02x} => Some({}),\n",
                item.ascii_alt, item.identifier
            ),
        );
    }
    sort_and_write(os, &items);

    write!(
        os,
        "            _ => None,
        }}
    }}

    /// Convert to a fallback ASCII `char` if possible.
    pub const fn to_fallback_ascii(self) -> Option<char> {{
        match self.0 {{
            0..127 => Some(self.0 as char),
"
    )
    .unwrap();

    let mut items = BTreeMap::new();
    for (_, item) in map_table.iter() {
        items.insert(
            item.ascii_alt,
            format!(
                "            {:#02x} => Some({:?}),\n",
                item.ascii_alt,
                item.ascii_fallback()
            ),
        );
    }
    sort_and_write(os, &items);

    write!(
        os,
        "            _ => None,
        }}
    }}
}}
"
    )
    .unwrap();
}

fn sort_and_write<KEY: Ord>(os: &mut dyn Write, items: &BTreeMap<KEY, String>) {
    let mut keys = items.keys().collect::<Vec<_>>();
    keys.sort();
    for key in keys {
        let item = items.get(key).unwrap();
        write!(os, "{}", item).unwrap();
    }
}

fn trim_quotes(s: &str) -> &str {
    let s = s.trim();
    if s.starts_with('"') && s.ends_with('"') && s.len() >= 2 {
        &s[1..s.len() - 1]
    } else {
        s
    }
}

fn parse_udlr(udlr: &str) -> u8 {
    let mut bits = 0;
    for c in udlr.chars() {
        match c {
            'u' => bits |= Udlr::SingleUp as u8,
            'd' => bits |= Udlr::SingleDown as u8,
            'l' => bits |= Udlr::SingleLeft as u8,
            'r' => bits |= Udlr::SingleRight as u8,
            _ => {}
        }
    }
    bits
}

#[allow(unused)]
struct BoxDrawingChar {
    identifier: String,
    unicode: u32,
    ascii_alt: u8,
    ascii_fallback: u8,
    udlr: u8,
    description: String,
}

impl BoxDrawingChar {
    pub const fn ascii_fallback(&self) -> char {
        self.ascii_fallback as char
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Udlr {
    SingleUp = 0b0000_0001,
    SingleRight = 0b0000_0010,
    SingleDown = 0b0000_0100,
    SingleLeft = 0b0000_1000,
}
